[workspace]
authors = ["runette <runette@gmail.com>"]
channels = ["conda-forge"]
name = "Conda"
platforms = ["win-64", "osx-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[target.win-64.dependencies]
mdal = "1.3.1.*"
gdal-csharp = "2.1.4.*"
pdal-c = "2.2.3.*"

[target.osx-64.dependencies]
mdal = "1.3.1.*"
gdal-csharp = "2.1.4.*"
pdal-c = "2.2.3.*"

[target.osx-arm64.dependencies]
mdal = "1.3.1.*"
gdal-csharp = "2.1.4.*"
pdal-c = "2.2.3.*"

[target.linux-64.dependencies]
mdal = "1.3.1.*"
gdal-csharp = "2.1.4.*"
pdal-c = "2.2.3.*"
