name: Build for Linux

on: workflow_dispatch

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-


      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64

      # Restore Linux SONAME symlinks
      - name: Restore native plugin symlinks
        run: |
          set -eux

          SRC="Assets/Conda/Plugins/x64"
          DST=$(find build -type d -path "*/StandaloneLinux64_Data/Plugins/x86_64" | head -1)

          echo "Plugin destination: $DST"

          sudo chown -R $(id -u):$(id -g) build

          rm -rf "$DST"
          mkdir -p "$DST"

          cp -a "$SRC"/. "$DST"/

          echo "Verifying symlinks..."
          find "$DST" -maxdepth 1 -type l | head

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
